set_property(GLOBAL PROPERTY USE_FOLDERS ON)



set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
 
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${ROOTPATH}/bin/debug)   

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${ROOTPATH}/bin/release)


#source_group(TREE ${CMAKE_SOURCE_DIR} FILES ${HEAD_FILES})
#source_group(TREE ${CMAKE_SOURCE_DIR} FILES ${SRC_FILES})
source_group("FORMS_SOURCE" FILES ${FORMS_SOURCE})
source_group("HEADERS_SOURCE" FILES ${HEADERS_SOURCE})
source_group("CPP_SOURCE" FILES ${CPP_SOURCE})
source_group("RES_SOURCE" FILES ${RES_SOURCE})

list(APPEND CMAKE_AUTOUIC_SEARCH_PATHS ${HEADERS_SOURCE})


add_executable(${PROJECT_NAME} ${FORMS_SOURCE} ${HEADERS_SOURCE} ${CPP_SOURCE} ${RES_SOURCE})

#set_property(TARGET ${TARGET} PROPERTY FOLDER "app/${TARGET}")

set_property(SOURCE ${CPP_SOURCE} APPEND PROPERTY OBJECT_DEPENDS "${FORMS_SOURCE}")
set_property(SOURCE ${CPP_SOURCE} PROPERTY FOLDER "${HEADERS_SOURCE}")
set_property(SOURCE ${CPP_SOURCE} PROPERTY FOLDER "${TARGET}")